# From https://raw.githubusercontent.com/weinholt/laesare/master/.travis.yml
env:
  matrix:
    - SCHEME="ChezScheme_master"

sudo: false
dist: bionic

addons:
  apt:
    packages:
      - chezscheme
      - libcurl4

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  - linux

compiler:
  - gcc

before_script:
  # Install Akku.scm and dependencies
  - gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 08272FBB54EEB5072D5BA930E33E61A2E9B8C3A2
  - curl -A "$TRAVIS_REPO_SLUG" -LO "https://archive.akkuscm.org/get-akku.sh{,.sig}"
  - gpg --verify get-akku.sh.sig get-akku.sh && bash get-akku.sh
  - ~/bin/akku install
  - export SCHEME_LIBRARY_PATH=$PWD/.akku/lib
  - export LIBCURL_SO="/usr/lib/x86_64-linux-gnu/libcurl.so.4"

script:
  - eval $(.akku/env -s)
  - ./tests/test-curl-scheme.sps
