name: CI

on: 
  push:
    branches: [master]


jobs:
  CI:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install Chez & Akku
        run: |
          sudo apt upgrade && sudo apt update
          sudo apt install -y curl
          sudo apt install -y chezscheme
          wget https://gitlab.com/akkuscm/akku/uploads/094ce726ce3c6cf8c14560f1e31aaea0/akku-1.1.0.amd64-linux.tar.xz -P /tmp
          cd /tmp
          tar -xf akku-1.1.0.amd64-linux.tar.xz 
          cd akku-1.1.0.amd64-linux/
          ./install.sh

      - name: Check out the repository
        uses: actions/checkout@master
      - name: Install Dependencies & Test 
        run: |
          $HOME/.local/bin/akku install
          export LIBCURL_SO="/usr/lib/x86_64-linux-gnu/libcurl.so.4"
          export SCHEME_LIBRARY_PATH=$PWD/.akku/lib
          eval $(.akku/env -s)
          ./tests/test-curl-scheme.sps
          echo "All tests passed!"
        
        
      